action_id: trunk-single-player-auto-upgrade
date: 2024-01-25 10:16:49
run: trunk upgrade cli --single-player-only -n --no-progress --on-upgrade=false --allow-daemon-start=false
run_from: ""
trigger: schedule 24h+1h
result:
  exit_code: 2816
  out: ""
  err: ""
timestamp: 1706177809
full_timestamp:
  nanos: 244036000
  seconds: 1706177809
trunk_version: 1.19.0
